/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.47
 * Generated at: 2025-10-30 18:33:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/workspaces/Parte_3_proyecto_aplicacion/apache-tomcat-10.1.47/webapps/Laboratorio2PaP/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664453478000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1664453510000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Registro de Turista - Turismo.uy</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/registration.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"registration-container\">\n");
      out.write("    <!-- Lado izquierdo: hero -->\n");
      out.write("    <div class=\"registration-hero\" role=\"banner\">\n");
      out.write("        <div class=\"hero-icon\" aria-hidden=\"true\">🧳</div>\n");
      out.write("        <h1>Regístrate como Turista</h1>\n");
      out.write("        <p>Únete para descubrir increíbles experiencias turísticas</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Lado derecho: formulario -->\n");
      out.write("    <div class=\"registration-form-section\" role=\"main\">\n");
      out.write("        <div class=\"form-header\">\n");
      out.write("            <h2>Registro de Turista</h2>\n");
      out.write("            <p>Completa tus datos para crear una cuenta</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Mensajes de error/éxito -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/includes/messages.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Formulario de registro -->\n");
      out.write("        <form method=\"post\" \n");
      out.write("              action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" \n");
      out.write("              enctype=\"multipart/form-data\"\n");
      out.write("              class=\"registration-form\"\n");
      out.write("              novalidate>\n");
      out.write("            <!-- Información de cuenta -->\n");
      out.write("            <fieldset>\n");
      out.write("                <legend>Información de Cuenta</legend>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"nickname\">Nickname <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"nickname\" \n");
      out.write("                               name=\"nickname\" \n");
      out.write("                               required \n");
      out.write("                               pattern=\"[A-Za-z0-9_]{4,20}\"\n");
      out.write("                               placeholder=\"Tu nombre de usuario único\"\n");
      out.write("                               autocomplete=\"username\"\n");
      out.write("                               autofocus>\n");
      out.write("                        <div class=\"form-hint\">4-20 caracteres, solo letras, números y guiones bajos</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"email\">Email <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"email\" \n");
      out.write("                               id=\"email\" \n");
      out.write("                               name=\"email\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"tu@email.com\"\n");
      out.write("                               autocomplete=\"email\">\n");
      out.write("                        <div class=\"form-hint\">Dirección de correo electrónico válida</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"password\">Contraseña <span class=\"required\">*</span></label>\n");
      out.write("                        <div class=\"password-input\">\n");
      out.write("                            <input type=\"password\" \n");
      out.write("                                   id=\"password\" \n");
      out.write("                                   name=\"password\" \n");
      out.write("                                   required\n");
      out.write("                                   placeholder=\"Tu contraseña\"\n");
      out.write("                                   autocomplete=\"new-password\"\n");
      out.write("                                   minlength=\"8\">\n");
      out.write("                            <button type=\"button\" \n");
      out.write("                                    class=\"toggle-password\" \n");
      out.write("                                    onclick=\"togglePassword('password')\">\n");
      out.write("                                <span>👁️</span>\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-hint\">Mínimo 8 caracteres</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"confirmPassword\">Confirmar Contraseña <span class=\"required\">*</span></label>\n");
      out.write("                        <div class=\"password-input\">\n");
      out.write("                            <input type=\"password\" \n");
      out.write("                                   id=\"confirmPassword\" \n");
      out.write("                                   name=\"confirmPassword\" \n");
      out.write("                                   required\n");
      out.write("                                   placeholder=\"Repite tu contraseña\"\n");
      out.write("                                   autocomplete=\"new-password\"\n");
      out.write("                                   minlength=\"8\">\n");
      out.write("                            <button type=\"button\" \n");
      out.write("                                    class=\"toggle-password\" \n");
      out.write("                                    onclick=\"togglePassword('confirmPassword')\">\n");
      out.write("                                <span>👁️</span>\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-hint\">Debe coincidir con la contraseña</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("            <!-- Información personal -->\n");
      out.write("            <fieldset>\n");
      out.write("                <legend>Información Personal</legend>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"firstName\">Nombre <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"firstName\" \n");
      out.write("                               name=\"firstName\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"Tu nombre\"\n");
      out.write("                               autocomplete=\"given-name\">\n");
      out.write("                        <div class=\"form-hint\">Tu nombre de pila</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"lastName\">Apellido <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"lastName\" \n");
      out.write("                               name=\"lastName\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"Tu apellido\"\n");
      out.write("                               autocomplete=\"family-name\">\n");
      out.write("                        <div class=\"form-hint\">Tu apellido</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"birthDate\">Fecha de Nacimiento <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"date\" \n");
      out.write("                               id=\"birthDate\" \n");
      out.write("                               name=\"birthDate\" \n");
      out.write("                               required\n");
      out.write("                               autocomplete=\"bday\">\n");
      out.write("                        <div class=\"form-hint\">Debes ser mayor de edad</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"nationality\">Nacionalidad <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"nationality\" \n");
      out.write("                               name=\"nationality\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"Tu nacionalidad\"\n");
      out.write("                               autocomplete=\"country-name\">\n");
      out.write("                        <div class=\"form-hint\">País de origen</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("            <!-- Imagen de perfil -->\n");
      out.write("            <fieldset>\n");
      out.write("                <legend>Imagen de Perfil</legend>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"profileImage\">Foto de Perfil (Opcional)</label>\n");
      out.write("                    <div class=\"file-input\">\n");
      out.write("                        <input type=\"file\" \n");
      out.write("                               id=\"profileImage\" \n");
      out.write("                               name=\"profileImage\"\n");
      out.write("                               accept=\"image/*\">\n");
      out.write("                        <label for=\"profileImage\" class=\"file-input-label\">\n");
      out.write("                            📷 Seleccionar imagen\n");
      out.write("                        </label>\n");
      out.write("                        <span class=\"file-name\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-hint\">JPG, PNG. Máximo 5MB</div>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("            <!-- Acciones del formulario -->\n");
      out.write("            <div class=\"form-actions\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("                    <span class=\"btn-icon\">✨</span>\n");
      out.write("                    Completar Registro\n");
      out.write("                </button>\n");
      out.write("                <div class=\"login-footer\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"back-link\">\n");
      out.write("                        Volver\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/app.js\"></script>\n");
      out.write("<script>\n");
      out.write("// Form validation\n");
      out.write("document.querySelector('.registration-form').addEventListener('submit', function(e) {\n");
      out.write("    let isValid = true;\n");
      out.write("    const password = document.getElementById('password').value;\n");
      out.write("    const confirmPassword = document.getElementById('confirmPassword').value;\n");
      out.write("    document.querySelectorAll('.error-field').forEach(el => el.classList.remove('error-field'));\n");
      out.write("    this.querySelectorAll('input[required]').forEach(input => {\n");
      out.write("        if (!input.value.trim()) {\n");
      out.write("            input.closest('.form-group').classList.add('error-field');\n");
      out.write("            isValid = false;\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    if (password !== confirmPassword) {\n");
      out.write("        document.getElementById('confirmPassword').closest('.form-group').classList.add('error-field');\n");
      out.write("        showMessage('error', 'Las contraseñas no coinciden');\n");
      out.write("        isValid = false;\n");
      out.write("    }\n");
      out.write("    const email = document.getElementById('email');\n");
      out.write("    if (email.value && !email.value.match(/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/)) {\n");
      out.write("        email.closest('.form-group').classList.add('error-field');\n");
      out.write("        showMessage('error', 'Email inválido');\n");
      out.write("        isValid = false;\n");
      out.write("    }\n");
      out.write("    if (!isValid) {\n");
      out.write("        e.preventDefault();\n");
      out.write("    } else {\n");
      out.write("        const submitBtn = this.querySelector('button[type=\"submit\"]');\n");
      out.write("        submitBtn.classList.add('loading');\n");
      out.write("        submitBtn.disabled = true;\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("// File preview\n");
      out.write("document.getElementById('profileImage').addEventListener('change', function(e) {\n");
      out.write("    const file = e.target.files[0];\n");
      out.write("    const fileNameSpan = this.parentElement.querySelector('.file-name');\n");
      out.write("    if (file) {\n");
      out.write("        fileNameSpan.textContent = file.name;\n");
      out.write("        this.nextElementSibling.textContent = '✅ ' + file.name;\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Registro - Sistema de Inscripciones</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-container {\n");
      out.write("            background: white;\n");
      out.write("            padding: 2rem;\n");
      out.write("            border-radius: 15px;\n");
      out.write("            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 500px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-header {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-header h1 {\n");
      out.write("            color: #333;\n");
      out.write("            font-size: 2rem;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .register-header p {\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            color: #333;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group input,\n");
      out.write("        .form-group select,\n");
      out.write("        .form-group textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.75rem;\n");
      out.write("            border: 2px solid #e1e5e9;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            transition: border-color 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group input:focus,\n");
      out.write("        .form-group select:focus,\n");
      out.write("        .form-group textarea:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #667eea;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .form-group textarea {\n");
      out.write("            resize: vertical;\n");
      out.write("            min-height: 80px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .tipo-usuario-group {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 1rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .tipo-usuario-option {\n");
      out.write("            flex: 1;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .tipo-usuario-option input[type=\"radio\"] {\n");
      out.write("            position: absolute;\n");
      out.write("            opacity: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .tipo-usuario-option label {\n");
      out.write("            display: block;\n");
      out.write("            padding: 1rem;\n");
      out.write("            border: 2px solid #e1e5e9;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            text-align: center;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .tipo-usuario-option input[type=\"radio\"]:checked + label {\n");
      out.write("            border-color: #667eea;\n");
      out.write("            background-color: #f8f9ff;\n");
      out.write("            color: #667eea;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .campos-especificos {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .campos-especificos.active {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 1rem;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: transform 0.2s ease;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .btn:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-message {\n");
      out.write("            background-color: #f8d7da;\n");
      out.write("            color: #721c24;\n");
      out.write("            padding: 1rem;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            border: 1px solid #f5c6cb;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .success-message {\n");
      out.write("            background-color: #d4edda;\n");
      out.write("            color: #155724;\n");
      out.write("            padding: 1rem;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            border: 1px solid #c3e6cb;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .login-link {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 1.5rem;\n");
      out.write("            padding-top: 1.5rem;\n");
      out.write("            border-top: 1px solid #e1e5e9;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .login-link a {\n");
      out.write("            color: #667eea;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .login-link a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"register-container\">\n");
      out.write("        <div class=\"register-header\">\n");
      out.write("            <h1>🎯 Registro</h1>\n");
      out.write("            <p>Crea tu cuenta en el sistema de inscripciones</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        \n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        \n");
      out.write("        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">\n");
      out.write("            \n");
      out.write("            <!-- Tipo de Usuario -->\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Tipo de Usuario</label>\n");
      out.write("                <div class=\"tipo-usuario-group\">\n");
      out.write("                    <div class=\"tipo-usuario-option\">\n");
      out.write("                        <input type=\"radio\" id=\"turista\" name=\"tipoUsuario\" value=\"turista\" \n");
      out.write("                               ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tipoUsuario eq 'turista' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" required>\n");
      out.write("                        <label for=\"turista\">🧑 Turista</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"tipo-usuario-option\">\n");
      out.write("                        <input type=\"radio\" id=\"proveedor\" name=\"tipoUsuario\" value=\"proveedor\" \n");
      out.write("                               ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tipoUsuario eq 'proveedor' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" required>\n");
      out.write("                        <label for=\"proveedor\">🏢 Proveedor</label>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Campos Básicos -->\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"nickname\">Nickname *</label>\n");
      out.write("                <input type=\"text\" id=\"nickname\" name=\"nickname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nickname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"email\">Email *</label>\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"nombre\">Nombre *</label>\n");
      out.write("                <input type=\"text\" id=\"nombre\" name=\"nombre\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nombre}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"apellido\">Apellido *</label>\n");
      out.write("                <input type=\"text\" id=\"apellido\" name=\"apellido\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apellido}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"fechaNacimiento\">Fecha de Nacimiento *</label>\n");
      out.write("                <input type=\"date\" id=\"fechaNacimiento\" name=\"fechaNacimiento\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fechaNacimiento}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Campos específicos para Turista -->\n");
      out.write("            <div id=\"campos-turista\" class=\"campos-especificos ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tipoUsuario eq 'turista' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"nacionalidad\">Nacionalidad *</label>\n");
      out.write("                    <input type=\"text\" id=\"nacionalidad\" name=\"nacionalidad\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nacionalidad}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Campos específicos para Proveedor -->\n");
      out.write("            <div id=\"campos-proveedor\" class=\"campos-especificos ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tipoUsuario eq 'proveedor' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"descripcion\">Descripción *</label>\n");
      out.write("                    <textarea id=\"descripcion\" name=\"descripcion\" placeholder=\"Describe tu empresa o servicios\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${descripcion}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"link\">Sitio Web</label>\n");
      out.write("                    <input type=\"url\" id=\"link\" name=\"link\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${link}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"https://tu-sitio-web.com\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <button type=\"submit\" class=\"btn\">\n");
      out.write("                🚀 Crear Cuenta\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("        <div class=\"login-link\">\n");
      out.write("            <p>¿Ya tienes cuenta? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Inicia sesión aquí</a></p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            const tipoUsuarioRadios = document.querySelectorAll('input[name=\"tipoUsuario\"]');\n");
      out.write("            const camposTurista = document.getElementById('campos-turista');\n");
      out.write("            const camposProveedor = document.getElementById('campos-proveedor');\n");
      out.write("            \n");
      out.write("            function toggleCamposEspecificos() {\n");
      out.write("                const tipoSeleccionado = document.querySelector('input[name=\"tipoUsuario\"]:checked').value;\n");
      out.write("                \n");
      out.write("                if (tipoSeleccionado === 'turista') {\n");
      out.write("                    camposTurista.classList.add('active');\n");
      out.write("                    camposProveedor.classList.remove('active');\n");
      out.write("                    document.getElementById('nacionalidad').setAttribute('required', '');\n");
      out.write("                    document.getElementById('descripcion').removeAttribute('required');\n");
      out.write("                } else if (tipoSeleccionado === 'proveedor') {\n");
      out.write("                    camposProveedor.classList.add('active');\n");
      out.write("                    camposTurista.classList.remove('active');\n");
      out.write("                    document.getElementById('descripcion').setAttribute('required', '');\n");
      out.write("                    document.getElementById('nacionalidad').removeAttribute('required');\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            tipoUsuarioRadios.forEach(radio => {\n");
      out.write("                radio.addEventListener('change', toggleCamposEspecificos);\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            // Ejecutar al cargar la página\n");
      out.write("            if (document.querySelector('input[name=\"tipoUsuario\"]:checked')) {\n");
      out.write("                toggleCamposEspecificos();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/register.jsp(411,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("            <div class=\"error-message\">\n");
        out.write("                <strong>Error:</strong> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("            </div>\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/register.jsp(417,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty success}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("            <div class=\"success-message\">\n");
        out.write("                <strong>Éxito:</strong> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("            </div>\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
