/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.47
 * Generated at: 2025-10-30 13:53:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Turismo.uy - Inicio de Sesión</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"hero-section\" role=\"banner\">\n");
      out.write("        <div class=\"hero-icon\" aria-hidden=\"true\">🏖️</div>\n");
      out.write("        <h1>Turismo.uy</h1>\n");
      out.write("        <p>Descubre las mejores experiencias turísticas de Uruguay</p>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"login-section\" role=\"main\">\n");
      out.write("        <div class=\"login-header\">\n");
      out.write("            <h2>Iniciar Sesión</h2>\n");
      out.write("            <p>Accede a tu cuenta para explorar actividades</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/includes/messages.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("        <form method=\"post\" \n");
      out.write("              action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" \n");
      out.write("              class=\"login-form\" \n");
      out.write("              novalidate \n");
      out.write("              autocomplete=\"on\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"username\">Nickname o Email <span class=\"required\" aria-hidden=\"true\">*</span></label>\n");
      out.write("                <input type=\"text\" \n");
      out.write("                       id=\"username\" \n");
      out.write("                       name=\"username\" \n");
      out.write("                       required \n");
      out.write("                       aria-required=\"true\"\n");
      out.write("                       aria-describedby=\"username-hint\"\n");
      out.write("                       placeholder=\"Ingresa tu nickname o email\"\n");
      out.write("                       autocomplete=\"username\"\n");
      out.write("                       minlength=\"4\"\n");
      out.write("                       maxlength=\"50\"\n");
      out.write("                       autofocus>\n");
      out.write("                <div id=\"username-hint\" class=\"form-hint\">Ingresa tu nombre de usuario o correo electrónico registrado</div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"password\">Contraseña <span class=\"required\" aria-hidden=\"true\">*</span></label>\n");
      out.write("                <div class=\"password-input\">\n");
      out.write("                    <input type=\"password\" \n");
      out.write("                           id=\"password\" \n");
      out.write("                           name=\"password\" \n");
      out.write("                           required \n");
      out.write("                           aria-required=\"true\"\n");
      out.write("                           aria-describedby=\"password-hint\"\n");
      out.write("                           placeholder=\"Ingresa tu contraseña\"\n");
      out.write("                           autocomplete=\"current-password\">\n");
      out.write("                    <button type=\"button\" \n");
      out.write("                            class=\"toggle-password\" \n");
      out.write("                            aria-label=\"Mostrar contraseña\" \n");
      out.write("                            title=\"Mostrar contraseña\"\n");
      out.write("                            tabindex=\"0\"\n");
      out.write("                            onclick=\"togglePassword('password')\">\n");
      out.write("                        <span aria-hidden=\"true\">👁️</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"password-hint\" class=\"form-hint\">Ingresa tu contraseña registrada</div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-actions\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("                    <span class=\"btn-icon\" aria-hidden=\"true\">🔒</span>\n");
      out.write("                    Iniciar Sesión\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div class=\"register-links\" role=\"navigation\">\n");
      out.write("            <p>¿No tienes cuenta? Regístrate como:</p>\n");
      out.write("            <div class=\"register-options\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register-tourist\" class=\"register-btn\" role=\"button\">\n");
      out.write("                    <span class=\"btn-icon\">🧳</span>\n");
      out.write("                    Turista\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register-provider\" class=\"register-btn\" role=\"button\">\n");
      out.write("                    <span class=\"btn-icon\">🏢</span>\n");
      out.write("                    Proveedor\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div style=\"margin-top: 15px;\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"help-link\">← Volver al inicio</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <footer class=\"login-footer\">\n");
      out.write("            <p>¿Necesitas ayuda? <a href=\"#\" class=\"help-link\">Contacta con soporte</a></p>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/app.js\"></script>\n");
      out.write("<script>\n");
      out.write("function togglePassword(inputId) {\n");
      out.write("    const input = document.getElementById(inputId);\n");
      out.write("    const button = input.nextElementSibling;\n");
      out.write("    \n");
      out.write("    if (input.type === 'password') {\n");
      out.write("        input.type = 'text';\n");
      out.write("        button.textContent = '🔒';\n");
      out.write("        button.setAttribute('aria-label', 'Ocultar contraseña');\n");
      out.write("        button.setAttribute('title', 'Ocultar contraseña');\n");
      out.write("    } else {\n");
      out.write("        input.type = 'password';\n");
      out.write("        button.textContent = '👁️';\n");
      out.write("        button.setAttribute('aria-label', 'Mostrar contraseña');\n");
      out.write("        button.setAttribute('title', 'Mostrar contraseña');\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("// Form validation\n");
      out.write("document.querySelector('form').addEventListener('submit', function(e) {\n");
      out.write("    const username = document.getElementById('username').value.trim();\n");
      out.write("    const password = document.getElementById('password').value;\n");
      out.write("    let isValid = true;\n");
      out.write("    \n");
      out.write("    // Clear previous error states\n");
      out.write("    document.querySelectorAll('.error-field').forEach(el => el.classList.remove('error-field'));\n");
      out.write("    \n");
      out.write("    if (!username) {\n");
      out.write("        document.getElementById('username').parentElement.classList.add('error-field');\n");
      out.write("        isValid = false;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    if (!password) {\n");
      out.write("        document.getElementById('password').parentElement.classList.add('error-field');\n");
      out.write("        isValid = false;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    if (!isValid) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        showMessage('error', 'Por favor completa todos los campos requeridos');\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
