/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.47
 * Generated at: 2025-10-30 14:04:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_002dtourist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Registro de Turista - Turismo.uy</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/registration.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"registration-container\">\n");
      out.write("    <!-- Lado izquierdo: hero -->\n");
      out.write("    <div class=\"registration-hero\" role=\"banner\">\n");
      out.write("        <div class=\"hero-icon\" aria-hidden=\"true\">🧳</div>\n");
      out.write("        <h1>Regístrate como Turista</h1>\n");
      out.write("        <p>Únete para descubrir increíbles experiencias turísticas</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Lado derecho: formulario -->\n");
      out.write("    <div class=\"registration-form-section\" role=\"main\">\n");
      out.write("        <div class=\"form-header\">\n");
      out.write("            <h2>Registro de Turista</h2>\n");
      out.write("            <p>Completa tus datos para crear una cuenta</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Mensajes de error/éxito -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/includes/messages.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Formulario de registro -->\n");
      out.write("        <form method=\"post\" \n");
      out.write("              action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register-tourist\" \n");
      out.write("              enctype=\"multipart/form-data\"\n");
      out.write("              class=\"registration-form\"\n");
      out.write("              novalidate>\n");
      out.write("            \n");
      out.write("            <!-- Información de cuenta -->\n");
      out.write("            <fieldset>\n");
      out.write("                <legend>Información de Cuenta</legend>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"nickname\">Nickname <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"nickname\" \n");
      out.write("                               name=\"nickname\" \n");
      out.write("                               required \n");
      out.write("                               pattern=\"[A-Za-z0-9_]{4,20}\"\n");
      out.write("                               placeholder=\"Tu nombre de usuario único\"\n");
      out.write("                               autocomplete=\"username\"\n");
      out.write("                               autofocus>\n");
      out.write("                        <div class=\"form-hint\">4-20 caracteres, solo letras, números y guiones bajos</div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"email\">Email <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"email\" \n");
      out.write("                               id=\"email\" \n");
      out.write("                               name=\"email\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"tu@email.com\"\n");
      out.write("                               autocomplete=\"email\">\n");
      out.write("                        <div class=\"form-hint\">Dirección de correo electrónico válida</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"password\">Contraseña <span class=\"required\">*</span></label>\n");
      out.write("                        <div class=\"password-input\">\n");
      out.write("                            <input type=\"password\" \n");
      out.write("                                   id=\"password\" \n");
      out.write("                                   name=\"password\" \n");
      out.write("                                   required\n");
      out.write("                                   placeholder=\"Tu contraseña\"\n");
      out.write("                                   autocomplete=\"new-password\"\n");
      out.write("                                   minlength=\"8\">\n");
      out.write("                            <button type=\"button\" \n");
      out.write("                                    class=\"toggle-password\" \n");
      out.write("                                    onclick=\"togglePassword('password')\">\n");
      out.write("                                <span>👁️</span>\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-hint\">Mínimo 8 caracteres</div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"confirmPassword\">Confirmar Contraseña <span class=\"required\">*</span></label>\n");
      out.write("                        <div class=\"password-input\">\n");
      out.write("                            <input type=\"password\" \n");
      out.write("                                   id=\"confirmPassword\" \n");
      out.write("                                   name=\"confirmPassword\" \n");
      out.write("                                   required\n");
      out.write("                                   placeholder=\"Repite tu contraseña\"\n");
      out.write("                                   autocomplete=\"new-password\"\n");
      out.write("                                   minlength=\"8\">\n");
      out.write("                            <button type=\"button\" \n");
      out.write("                                    class=\"toggle-password\" \n");
      out.write("                                    onclick=\"togglePassword('confirmPassword')\">\n");
      out.write("                                <span>👁️</span>\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-hint\">Debe coincidir con la contraseña</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("\n");
      out.write("            <!-- Información personal -->\n");
      out.write("            <fieldset>\n");
      out.write("                <legend>Información Personal</legend>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"firstName\">Nombre <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"firstName\" \n");
      out.write("                               name=\"firstName\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"Tu nombre\"\n");
      out.write("                               autocomplete=\"given-name\">\n");
      out.write("                        <div class=\"form-hint\">Tu nombre de pila</div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"lastName\">Apellido <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"lastName\" \n");
      out.write("                               name=\"lastName\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"Tu apellido\"\n");
      out.write("                               autocomplete=\"family-name\">\n");
      out.write("                        <div class=\"form-hint\">Tu apellido</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"birthDate\">Fecha de Nacimiento <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"date\" \n");
      out.write("                               id=\"birthDate\" \n");
      out.write("                               name=\"birthDate\" \n");
      out.write("                               required\n");
      out.write("                               autocomplete=\"bday\">\n");
      out.write("                        <div class=\"form-hint\">Debes ser mayor de edad</div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"nationality\">Nacionalidad <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" \n");
      out.write("                               id=\"nationality\" \n");
      out.write("                               name=\"nationality\" \n");
      out.write("                               required\n");
      out.write("                               placeholder=\"Tu nacionalidad\"\n");
      out.write("                               autocomplete=\"country-name\">\n");
      out.write("                        <div class=\"form-hint\">País de origen</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("\n");
      out.write("            <!-- Imagen de perfil -->\n");
      out.write("            <fieldset>\n");
      out.write("                <legend>Imagen de Perfil</legend>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"profileImage\">Foto de Perfil (Opcional)</label>\n");
      out.write("                    <div class=\"file-input\">\n");
      out.write("                        <input type=\"file\" \n");
      out.write("                               id=\"profileImage\" \n");
      out.write("                               name=\"profileImage\"\n");
      out.write("                               accept=\"image/*\">\n");
      out.write("                        <label for=\"profileImage\" class=\"file-input-label\">\n");
      out.write("                            📷 Seleccionar imagen\n");
      out.write("                        </label>\n");
      out.write("                        <span class=\"file-name\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-hint\">JPG, PNG. Máximo 5MB</div>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("\n");
      out.write("            <!-- Acciones del formulario -->\n");
      out.write("            <div class=\"form-actions\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("                    <span class=\"btn-icon\">✨</span>\n");
      out.write("                    Completar Registro\n");
      out.write("                </button>\n");
      out.write("                \n");
      out.write("                <div class=\"login-footer\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"back-link\">\n");
      out.write("                        Volver\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/app.js\"></script>\n");
      out.write("<script>\n");
      out.write("// Form validation\n");
      out.write("document.querySelector('.registration-form').addEventListener('submit', function(e) {\n");
      out.write("    let isValid = true;\n");
      out.write("    const password = document.getElementById('password').value;\n");
      out.write("    const confirmPassword = document.getElementById('confirmPassword').value;\n");
      out.write("    \n");
      out.write("    document.querySelectorAll('.error-field').forEach(el => el.classList.remove('error-field'));\n");
      out.write("    \n");
      out.write("    this.querySelectorAll('input[required]').forEach(input => {\n");
      out.write("        if (!input.value.trim()) {\n");
      out.write("            input.closest('.form-group').classList.add('error-field');\n");
      out.write("            isValid = false;\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    if (password !== confirmPassword) {\n");
      out.write("        document.getElementById('confirmPassword').closest('.form-group').classList.add('error-field');\n");
      out.write("        showMessage('error', 'Las contraseñas no coinciden');\n");
      out.write("        isValid = false;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    const email = document.getElementById('email');\n");
      out.write("    if (email.value && !email.value.match(/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/)) {\n");
      out.write("        email.closest('.form-group').classList.add('error-field');\n");
      out.write("        showMessage('error', 'Email inválido');\n");
      out.write("        isValid = false;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    if (!isValid) {\n");
      out.write("        e.preventDefault();\n");
      out.write("    } else {\n");
      out.write("        const submitBtn = this.querySelector('button[type=\"submit\"]');\n");
      out.write("        submitBtn.classList.add('loading');\n");
      out.write("        submitBtn.disabled = true;\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("\n");
      out.write("// File preview\n");
      out.write("document.getElementById('profileImage').addEventListener('change', function(e) {\n");
      out.write("    const file = e.target.files[0];\n");
      out.write("    const fileNameSpan = this.parentElement.querySelector('.file-name');\n");
      out.write("    if (file) {\n");
      out.write("        fileNameSpan.textContent = file.name;\n");
      out.write("        this.nextElementSibling.textContent = '✅ ' + file.name;\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
